### ISSUE TITLE
Title doesn't  change  when updating

### ISSUE THREAD

**Issue by dkreft** [benjick/react-doc-title#1]
I've got a  situation where the title of my document isn't known until a record finishes loading (via a Redux Saga), so when I use either `useTitle()` or `<Title/>`, the page title, my  document title never changes.

The following diff fixes this problem. Would you consider applying this patch?

```diff
diff --git a/src/index.js b/src/index.js
index face2f2..a777423 100644
--- a/src/index.js
+++ b/src/index.js
@@ -4,7 +4,7 @@ import {Provider, Context} from './useTitles'
 
 export function useTitle(string) {
   const context = useContext(Context)
-  useEffect(() => context.register({string}), [])
+  useEffect(() => context.register({string}), [string, context])
 }
 
 export function Title({string}) {
```

**Comment by benjick** [comment]
Hey!

Yes absolutely! Please send a PR and I'll merge. Cheers!

**Comment by dkreft** [comment]
The only problem is  that I went to run the unit tests and it blew up, big time. This, coupled with a lot  of noise during `npm i` (see below) also made me a bit nervous. Have you run `npm audit` on your package lately?

```
$ npm run test

> react-doc-title@1.0.0 test /workplace/react-doc-title
> cross-env CI=1 react-scripts test --env=jsdom

FAIL src/useTitles.spec.js
  ● Test suite failed to run

    ReferenceError: [BABEL] /workplace/react-doc-title/src/useTitles.spec.js: Unknown option: base.configFile. Check out http://babeljs.io/docs/usage/options/ for more information about options.

    A common cause of this error is the presence of a configuration options object without the corresponding preset name. Example:

    Invalid:
      `{ presets: [{option: value}] }`
    Valid:
      `{ presets: [['presetName', {option: value}]] }`

    For more detailed information on preset configuration, please see https://babeljs.io/docs/en/plugins#pluginpresets-options.

      at Logger.error (node_modules/babel-core/lib/transformation/file/logger.js:41:11)
      at OptionManager.mergeOptions (node_modules/babel-core/lib/transformation/file/options/option-manager.js:226:20)
      at OptionManager.init (node_modules/babel-core/lib/transformation/file/options/option-manager.js:368:12)
      at File.initOptions (node_modules/babel-core/lib/transformation/file/index.js:212:65)
      at new File (node_modules/babel-core/lib/transformation/file/index.js:135:24)
      at Pipeline.transform (node_modules/babel-core/lib/transformation/pipeline.js:46:16)

Test Suites: 1 failed, 1 total
Tests:       0 total
Snapshots:   0 total
Time:        1.207s
Ran all test suites.
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! react-doc-title@1.0.0 test: `cross-env CI=1 react-scripts test --env=jsdom`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the react-doc-title@1.0.0 test script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/dkreft/.npm/_logs/2020-03-20T21_56_06_030Z-debug.log
```

**Comment by benjick** [comment]
I've published a new version with this change 👍

**Comment by dkreft** [comment]
Thank you, Max.

-dan
